### ISSUE TITLE
Define an issue template for capturing feedback

### ISSUE THREAD

**Issue by poorgeek** [ThePacielloGroup/VFO-standards-support#11]
The [Reporting Issues section of the README](https://github.com/ThePacielloGroup/VFO-standards-support#reporting-issues) define elements to include in a new issue. We should utilize [Github's issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) for defining what this looks like so that issue submitters don't have to copy , or remember, the template themselves.

**Comment by stevefaulkner** [comment]
@poorgeek I agree, can you do that?

**Comment by poorgeek** [comment]
Yes. I'll submit a PR for it. I don't have rights to self-assign the issue to myself.
